FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.9-run

WORKDIR /opt/k3s_context

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY main.py ./main.py

CMD ["python", "main.py"]
